### ISSUE TITLE
Selenium...

### ISSUE THREAD

**Issue by Lars132** [raptored01/whatsapp_hack#2]
Hello guys, I'm beginner and I don't know what do it means:

Traceback (most recent call last):
  File "grabber.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'

I installed the requirements and it did not work anyway.
My apologies for my English...

**Comment by raptored01** [comment]
Probably you did not in fact install selenium.
Try `pip install selenium`

**Comment by mandiri1155** [comment]
Tidak bisa
